config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users

  resources :books, only: [:new, :index, :show, :create, :edit, :destroy, :update]
  resources :users, only: [:new, :index, :show, :create, :edit, :destroy, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :image
  def get_image
    if image.attached?
      image
    else
      'abcd.jpg'
    end
  end
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'abcd.jpg'
    end
  end
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true, length: { minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
        <%= form_with model: @book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title,  class:"form-control"%>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update Book', class:"btn btn-success" %>
          </div>
        <% end %>
        <a><%= link_to "Show", "/books/#{@book.id}" %></a> 	|
        <a class="back" href="/books">Back</a>
        </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
         <%= image_tag @user.get_profile_image %>
      <table class="table">
       <tbody>
         <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%=  @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%=  @user.introduction %></th>
          </tr>
        </tbody>
        </table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block edit_user_31901" href="/users/<%= @user.id %>/edit">
    <i class="fas fa-user-cog"></i> 
</a></div>


<h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title,  class:"form-control"%>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>


</div>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to "/users/#{book.user_id}" do %>
                  <%= image_tag book.get_image %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>

      </table>

      </div>
    </div>
  </div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<main>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
         <%= image_tag @user.get_profile_image %>
      <table class="table">
       <tbody>
         <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%=  @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%=  @user.introduction %></th>
          </tr>
        </tbody>
        </table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block edit_user_31901" href="/users/<%= @user.id %>/edit">
    <i class="fas fa-user-cog"></i>
</a></div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @newbook do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title,  class:"form-control"%>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody><tr>
          <td>
            <a href="/users/<%= @user.id %>">
            <%= image_tag @book.get_image %><br>
            <%= @user.name %>
            </a>
          </td>
          <td><a><%= link_to @book.title, book_path(@book.id) %></a></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success edit_book_24573"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger destroy_book_24573" %></td>
          <% end %>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>
</main>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
     

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In<i class="fas fa-book"></i> <strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', "/users/sign_in", class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', "/users/sign_up", class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>


    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
<%= link_to root_path, class: 'navbar-brand' do %>
  <span>Bookers</span>
<% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
        <ul class="navbar-nav ml-auto">
          
<li>
  <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
    <i class="fas fa-home"></i>Home
  <% end %>
</li>

<li>
  <%= link_to users_path,class: 'nav-link text-light' do %>
    <i class="fas fa-users"></i>Users
  <% end %>
</li>

<li>
  <%= link_to books_path,class: 'nav-link text-light' do %>
    <i class="fas fa-book-open"></i>Books
  <% end %>
</li>


<li>
  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
    <i class="fas fa-sign-out-alt"></i>Log out
  <% end %>
</li>
        </ul>
      </div>
    </div>
  </nav>
  　　<% else %>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
<%= link_to root_path, class: 'navbar-brand' do %>
  <span>Bookers</span>
<% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

<li>
  <%= link_to root_path, class: 'nav-link text-light' do %>
    <i class="fas fa-home"></i>Home
  <% end %>
</li>
           
<li>
  <%= link_to about_path, class: 'nav-link text-light' do %>
    <i class="fas fa-link"></i>About
  <% end %>
</li>   

<li>
  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
    <i class="fas fa-user-plus"></i>Sign up 
  <% end %>
</li>   

<li>
  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
    <i class="fas fa-sign-in-alt"></i>Log in
  <% end %>
</li>   
        </ul>
      </div>
    </div>
  </nav>
  　　<% end %>
　　</header>
      <p class="notice"><%= notice %></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
   <div class="container">
   <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
       <% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
      <%= form_with model: @user do |f| %>
         <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name,  class:"form-control"%>
        </div>
        
       <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class:"form-control-file user_image" %>  
        </div>
        
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
           <%= f.text_area :introduction, class:"form-control introduction" %>
        </div>
        <div class="form-group">
           <%= f.submit "Update User", class:"btn btn-secondary" %>
          
        </div>
  </form>  
  <% end %>
  
  
  </div>
  </div>
  
        </div>
</main>

app/views/users/index.html.erb
<% if @book.errors.any? %>
  <%= @list.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image %>
      <table class="table">
       <tbody>
         <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%=  @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%=  @user.introduction %></th>
          </tr>
        </tbody>
        </table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block edit_user_31901" href="/users/<%= @user.id %>/edit">
    <i class="fas fa-user-cog"></i> 
</a></div>


      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title,  class:"form-control"%>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>
    </div>
    
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= image_tag user.get_profile_image %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", "/users/#{user.id}" %></td>
      </tr>
  	<% end %>
  </tbody>
</table>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
         <%= image_tag @user.get_profile_image %>
      <table class="table">
       <tbody>
         <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%=  @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%=  @user.introduction %></th>
          </tr>
        </tbody>
        </table>

<div class="row">
  <a class="btn btn-outline-secondary btn-block edit_user_31901" href="/users/<%= @user.id %>/edit">
    <i class="fas fa-user-cog"></i> 
</a></div>


<h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title,  class:"form-control"%>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>


</div>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to "/users/#{book.user_id}" do %>
                  <%= image_tag book.get_image %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>

      </table>

      </div>
    </div>
  </div>